### PR TITLE
Use echo -e instead of echo

### PR DESCRIPTION
**Pull request by barni2000**
Use echo -e instead of echo for module.prop generation, because echo will not resolve \n.

### CODE REVIEW

**Comment by edisionnano** [comment]
@barni2000 Doss the module this script produces actually work for you?

**Comment by barni2000** [comment]
With this fix i can install the module.

**Comment by edisionnano** [comment]
> With this fix i can install the module.

but does the module work?

**Comment by barni2000** [comment]
The vulkan lib is replaced after i have installed the module, but the vulkaninfo is not working after.

**Comment by edisionnano** [comment]
> The vulkan lib is replaced after i have installed the module, but the vulkaninfo is not working after.

so the moduld isnt working

**Pull request merged**
